application:
  title: JSConf Colombia 2016 | CFP
  url: http://cfp.jsconf.co
  email: hola@jsconf.co
  eventurl: http://jsconf.co
  event_location: Medellin, Colombia
  enddate: Jun. 13th, 2016
  show_submission_count: true
  airport: BOG
  arrival: 2016-10-05
  departure: 2016-10-10
  secure_ssl: false
  online_conference: false
  date_format: d/m/Y
  date_timezone: "GMT-5"
  coc_link: http://jsconf.com/codeofconduct.html

api:
  enabled: false

cache:
  enabled: false

database:
  host: 127.0.0.1
  database: cfp
  dsn: mysql:dbname=cfp;host=127.0.0.1
  user: root
  password: ~

log:
  level: error

mail:
  host: ~
  port: ~
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~

talk:
  categories:
    3d_webgl_vr: 3D / WebGL / VR
    async: Async
    art: Art
    api: API
    audio_music: Audio &amp; Music
    circuit_breakers: Circuit Breakers
    continuous_delivery: Continuous Delivery
    data_visualization: Data Visualization
    database_big: Database / Big Data
    dev_ops: Dev Ops
    dev_tools: Dev Tools
    distributed_programming: Distributed Programming
    es_next: ES 6 | 2015 | 2016 | Next
    functional_programming: Functional Programming
    hardware: Hardware
    http_microservices: HTTP Microservices
    machine_learning: Machine Learning with JS
    new_frontend_technologies: "New frontend technologies: React / Redux / Angular 2 / Ember 2"
    nodejs: Node.js
    other_js_languages: "Other JS Languages: TypeScript, Flow, Dart, ClojureScript, Elm, CoffeeScript"
    performance: Performance
    reactive_programming: Reactive Programming
    security: Security
    testing: Testing
    ui_ux: UI/UX
    other: Other
  levels:
    entry: Entry level
    mid: Mid-level
    advanced: Advanced
  types:
    talk: Talk (35 min)
    workshop: Workshop (1:30 hrs)

security:
  firewalls:
    secured_area:
      form_forgot:
        csrf_parameter: _csrf_security_token
        csrf_token_id: forgot_password
