application:
  title: JSConf Colombia 2016 | CFP
  url: http://cfp.jsconf.co
  email: hola@jsconf.co
  eventurl: http://jsconf.co
  event_location: Medellin, Colombia
  enddate: Jun. 13th, 2016
  show_submission_count: true
  airport: BOG
  arrival: 2016-10-05
  departure: 2016-10-10
  secure_ssl: false
  online_conference: false
  date_format: d/m/Y
  date_timezone: "GMT-5"

api:
  enabled: false

cache:
  enabled: false

database:
  host: 127.0.0.1
  database: cfp
  dsn: mysql:dbname=cfp;host=127.0.0.1
  user: root
  password: ~

log:
  level: error

mail:
  host: ~
  port: ~
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~
